/**
 * 페이지 컨텍스트에서 실행되는 스크립트.
 *
 * 여기서만 하는 일: 유튜브 player response에서 자막 트랙 목록을 확보하고,
 * timedtext(json3)를 실제로 내려받아 cue 배열로 정규화한 뒤 content script로 넘긴다.
 *
 * 페이지 컨텍스트여야 하는 이유 — timedtext 요청은 youtube.com 오리진 + 쿠키
 * 컨텍스트에서 나가야 하고, window.ytInitialPlayerResponse 는 격리 환경에서 안 보인다.
 *
 * 향후 NetflixAdapter 는 이 파일과 같은 위치(페이지 컨텍스트)에서 동작하며,
 * 동일한 CUES 메시지 형태로 결과를 넘기면 공통 레이어를 그대로 재사용한다.
 */
(() => {
  'use strict';

  const CHANNEL = 'LANGFLIX_JP';
  const post = (type, payload) =>
    window.postMessage({ __langflix: CHANNEL, type, payload }, '*');

  /** 같은 영상에 대해 중복 처리하지 않기 위한 가드 */
  let handledVideoId = null;

  function getCaptionTracks(playerResponse) {
    return (
      playerResponse &&
      playerResponse.captions &&
      playerResponse.captions.playerCaptionsTracklistRenderer &&
      playerResponse.captions.playerCaptionsTracklistRenderer.captionTracks
    ) || null;
  }

  /** 정식 자막(non-ASR)을 자동생성 자막보다 우선한다. */
  function pickTrack(tracks, langPrefix) {
    if (!tracks) return null;
    const matched = tracks.filter((t) =>
      String(t.languageCode || '').toLowerCase().startsWith(langPrefix)
    );
    if (!matched.length) return null;
    return matched.find((t) => t.kind !== 'asr') || matched[0];
  }

  /**
   * @param {string} baseUrl captionTracks[].baseUrl
   * @param {string} [tlang] 지정 시 유튜브 자동 번역 트랙을 요청
   * @returns {Promise<Array<{start:number,end:number,text:string}>>}
   */
  async function fetchCues(baseUrl, tlang) {
    const url = new URL(baseUrl, location.origin);
    url.searchParams.set('fmt', 'json3');
    if (tlang) url.searchParams.set('tlang', tlang);

    const res = await fetch(url.toString(), { credentials: 'include' });
    if (!res.ok) throw new Error('timedtext HTTP ' + res.status);
    const json = await res.json();

    return (json.events || [])
      .filter((e) => Array.isArray(e.segs))
      .map((e) => {
        const start = (e.tStartMs || 0) / 1000;
        const text = e.segs
          .map((s) => s.utf8 || '')
          .join('')
          .replace(/\s*\n\s*/g, ' ')
          .trim();
        return { start, end: start + (e.dDurationMs || 0) / 1000, text };
      })
      .filter((c) => c.text);
  }

  async function handlePlayerResponse(playerResponse) {
    const videoId =
      playerResponse &&
      playerResponse.videoDetails &&
      playerResponse.videoDetails.videoId;
    if (!videoId || videoId === handledVideoId) return;
    handledVideoId = videoId;

    try {
      const tracks = getCaptionTracks(playerResponse);
      const ja = pickTrack(tracks, 'ja');

      if (!ja) {
        post('NO_JA_TRACK', {
          videoId,
          available: (tracks || []).map((t) => t.languageCode)
        });
        return;
      }

      // 한국어는 정식 트랙이 있으면 그걸 쓰고, 없으면 유튜브 자동 번역으로 대체한다.
      // (PoC 한정. 실제 서비스에서는 백엔드 LLM 번역 + 캐시로 교체한다.)
      const koTrack = pickTrack(tracks, 'ko');
      const [jaCues, koCues] = await Promise.all([
        fetchCues(ja.baseUrl),
        koTrack
          ? fetchCues(koTrack.baseUrl)
          : fetchCues(ja.baseUrl, 'ko').catch(() => [])
      ]);

      post('CUES', {
        videoId,
        ja: jaCues,
        ko: koCues,
        meta: {
          jaIsAutoGenerated: ja.kind === 'asr',
          koSource: koTrack ? 'native' : 'youtube-auto-translate'
        }
      });
    } catch (err) {
      handledVideoId = null; // 실패한 영상은 다시 시도할 수 있게 되돌린다
      post('ERROR', { videoId, message: String(err) });
    }
  }

  // --- player response 수집 경로 1: SPA 전환 시 나가는 player API 응답 가로채기 ---
  const originalFetch = window.fetch;
  window.fetch = function (...args) {
    const promise = originalFetch.apply(this, args);
    try {
      const input = args[0];
      const url = typeof input === 'string' ? input : (input && input.url) || '';
      if (url.includes('/youtubei/v1/player')) {
        promise
          .then((res) => res.clone().json())
          .then(handlePlayerResponse)
          .catch(() => {});
      }
    } catch (_) {
      /* 가로채기 실패가 원래 요청을 막아서는 안 된다 */
    }
    return promise;
  };

  // --- player response 수집 경로 2: 최초 로드 시 HTML에 박혀 오는 값 ---
  let polls = 0;
  const timer = setInterval(() => {
    if (window.ytInitialPlayerResponse) {
      handlePlayerResponse(window.ytInitialPlayerResponse);
      clearInterval(timer);
    } else if (++polls > 100) {
      clearInterval(timer);
    }
  }, 100);
})();
