// Package dict looks up dictionary entries for a single word in context.
//
// Why this is not a data file: there is no usable open Japanese-Korean
// dictionary. JMdict ships English, German, Russian and others but no Korean;
// KANJIDIC2 gives only the Sino-Korean reading of a kanji, not word meanings;
// 국립국어원's multilingual dictionary is headword-Korean, so the reverse
// direction has almost no coverage. So the entry is generated by the model and
// cached forever — the cache is the dictionary, and it grows with use.
//
// The lookup is context-aware on purpose. "ぶん" is 文/分/物 depending on the
// line it sits in, and a learner reading subtitles needs the sense that is
// actually being used, not an alphabetical list of homographs.
package dict

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"strings"
	"sync"
)

// Request is one word to look up, with the sentence it appeared in.
type Request struct {
	Surface string `json:"surface"`           // as written in the subtitle
	Lemma   string `json:"lemma,omitempty"`   // dictionary form from the analyzer
	Reading string `json:"reading,omitempty"` // hiragana reading, if known
	POS     string `json:"pos,omitempty"`
	Context string `json:"context,omitempty"` // the whole subtitle line
}

// Sense is one meaning of the headword. Gloss is in the learner's language.
type Sense struct {
	POS   string `json:"pos,omitempty"`
	Gloss string `json:"gloss"`
	Note  string `json:"note,omitempty"`
}

// Example is a short sentence using the word, with its translation.
type Example struct {
	Text        string `json:"text"`
	Translation string `json:"translation,omitempty"`
}

// Entry is what the tooltip renders. Every field except Headword may be empty —
// the client must degrade rather than assume.
type Entry struct {
	Headword    string    `json:"headword"`
	Reading     string    `json:"reading,omitempty"`
	POS         string    `json:"pos,omitempty"`
	JLPT        string    `json:"jlpt,omitempty"`
	Senses      []Sense   `json:"senses,omitempty"`
	ContextNote string    `json:"context_note,omitempty"` // how the word is used in *this* line
	InContext   string    `json:"in_context,omitempty"`   // the one meaning that fits this line
	Examples    []Example `json:"examples,omitempty"`
	Cached      bool      `json:"cached"`
}

// Provider resolves a batch of words. Batching matters: a learner clicking
// through a line should not pay one round trip per word.
type Provider interface {
	Lookup(ctx context.Context, sourceLang, targetLang, level string, reqs []Request) ([]Entry, error)
	Name() string
}

// Stub is used when no API key is configured. It returns empty entries rather
// than an error, so the extension's fallback path (machine-translating the
// surface) stays reachable and /healthz can report dict="stub" honestly.
type Stub struct{}

func (Stub) Name() string { return "stub" }

func (Stub) Lookup(_ context.Context, _, _, _ string, reqs []Request) ([]Entry, error) {
	out := make([]Entry, len(reqs))
	for i, r := range reqs {
		out[i] = Entry{Headword: firstNonEmpty(r.Lemma, r.Surface)}
	}
	return out, nil
}

// Cached memoises lookups. The key includes the context because the entry is
// context-aware: the same word in a different line gets a different note and a
// different "meaning here". Re-watching a scene is free; meeting the word in a
// new line costs one request.
type Cached struct {
	inner Provider
	mu    sync.RWMutex
	cache map[string]Entry
	store *fileCache // nil when persistence is not configured
}

func NewCached(inner Provider) *Cached {
	return &Cached{inner: inner, cache: make(map[string]Entry)}
}

func (c *Cached) Name() string { return c.inner.Name() }

// Len reports how many entries are memoised — the size of the dictionary built
// so far.
func (c *Cached) Len() int {
	c.mu.RLock()
	defer c.mu.RUnlock()
	return len(c.cache)
}

func (c *Cached) Lookup(ctx context.Context, src, tgt, level string, reqs []Request) ([]Entry, error) {
	entries := make([]Entry, len(reqs))
	var missIdx []int
	var missReq []Request

	c.mu.RLock()
	for i, r := range reqs {
		if hit, ok := c.cache[key(src, tgt, r)]; ok {
			hit.Cached = true
			entries[i] = hit
			continue
		}
		missIdx = append(missIdx, i)
		missReq = append(missReq, r)
	}
	c.mu.RUnlock()

	if len(missReq) == 0 {
		return entries, nil
	}

	fresh, err := c.inner.Lookup(ctx, src, tgt, level, missReq)
	if err != nil {
		return nil, err
	}
	if len(fresh) != len(missReq) {
		return nil, errCount(len(fresh), len(missReq))
	}

	c.mu.Lock()
	for n, i := range missIdx {
		entries[i] = fresh[n]
		// An empty entry means the provider had nothing to say; caching it
		// would make the miss permanent.
		if len(fresh[n].Senses) > 0 {
			c.cache[key(src, tgt, missReq[n])] = fresh[n]
		}
	}
	snapshot := c.snapshotLocked()
	c.mu.Unlock()

	if c.store != nil {
		c.store.write(snapshot)
	}
	return entries, nil
}

// snapshot copies the memoised entries. The file cache writes off the request
// path, so it needs a value that will not change under it.
func (c *Cached) snapshot() map[string]Entry {
	c.mu.RLock()
	defer c.mu.RUnlock()
	return c.snapshotLocked()
}

func (c *Cached) snapshotLocked() map[string]Entry {
	out := make(map[string]Entry, len(c.cache))
	for k, v := range c.cache {
		out[k] = v
	}
	return out
}

// key identifies a lookup. Surface and lemma both matter (conjugated forms map
// to the same lemma but the learner clicked a specific surface), and the
// context is hashed so the key stays short regardless of line length.
func key(src, tgt string, r Request) string {
	sum := sha256.Sum256([]byte(r.Context))
	return strings.Join([]string{
		src, tgt,
		firstNonEmpty(r.Lemma, r.Surface),
		r.Surface,
		r.POS,
		hex.EncodeToString(sum[:8]),
	}, "|")
}

func firstNonEmpty(values ...string) string {
	for _, v := range values {
		if strings.TrimSpace(v) != "" {
			return v
		}
	}
	return ""
}
